// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for CrossRegionParamtersFunction
 */
export interface CrossRegionParamtersFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambdas/cross-region-parameters/cross-region-paramters.
 */
export class CrossRegionParamtersFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: CrossRegionParamtersFunctionProps) {
    super(scope, id, {
      description: 'src/lambdas/cross-region-parameters/cross-region-paramters.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/lambdas/cross-region-parameters/cross-region-paramters.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}